workspace:
  base: /go
  path: src/github.com/${DRONE_REPO}

pipeline:
  download-vendor:
    image: billyteves/alpine-golang-glide:1.2.0
    commands:
     - glide install -v

  build:
    image: golang
    commands:
    - go build -v
    environment:
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64

  docker:
    image: plugins/docker
    repo: twister915/acme-sidecar
    secrets: [docker_username, docker_password]
    tags:
    - $${DRONE_COMMIT_SHA:0:12}
